[project]
name = "Gald example"

[sources]
files = ["src/example.cpp"]

[includes]
dirs = ['include']

[compiler]
language = "g++"
enableStdOption = true
standard = "c++17"
options = ["$(ncursesw5-config --libs)", "$(ncursesw5-config --cflags)"]

[output]
name = "example"
