name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: apt update && apt install -y libncurses5-dev libncursesw5-dev
    - name: make build
      run: make build
